// Copyright (c) 2024-2025 SUV Lab, Chungbuk National University
// Author    : Gonapinuwala Lahiru Sandaruwan
// Sub-author: MinKyu Kim
// Supervisor: Prof. SungTae Moon - Project lead & research supervision
// Licensed under the BSD-3-Clause License.
// See LICENSE file in the project root for full license information.

#include "Widgets/RealGazeboMainWidget.h"
#include "Engine/World.h"
#include "Engine/Engine.h"
#include "Components/ListView.h"
#include "Components/TextBlock.h"
#include "Components/Button.h"
#include "Components/Border.h"
#include "TimerManager.h"
#include "RealGazeboUI.h"
#include "Widgets/RealGazeboVehicleEntry.h"
#include "ViewerController/RealGazeboViewerDirector.h"
#include "Vehicles/VehicleBasePawn.h"
#include "Kismet/GameplayStatics.h"

URealGazeboMainWidget::URealGazeboMainWidget(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
{
    // Set default values
    UpdateFrequency = 30.0f;
    MaxDisplayVehicles = 256;
    FadeDuration = 1.0f;

    // Initialize tracking variables
    LastVehicleCount = 0;
    bLastConnectionStatus = false;
    CurrentSelectedVehicleID = FVehicleID(0, 0); // Invalid ID as default
    FadeElapsedTime = 0.0f;

    // Enable ticking for real-time updates
    bIsFocusable = false;
    SetVisibility(ESlateVisibility::SelfHitTestInvisible);
}

void URealGazeboMainWidget::NativeConstruct()
{
    Super::NativeConstruct();
    
    // Constructing UI
    
    // Initialize subsystem connection
    InitializeSubsystemConnection();
    
    // Setup ListView event bindings
    if (VehicleListView)
    {
        VehicleListView->OnItemSelectionChanged().AddUObject(this, &URealGazeboMainWidget::OnVehicleItemSelectionChanged);

        // Bind entry widget generation event to handle newly created/recycled widgets
        VehicleListView->OnEntryWidgetGenerated().AddUObject(this, &URealGazeboMainWidget::OnEntryWidgetGenerated);

        // ListView events bound
    }
    else
    {
        UE_LOG(LogRealGazeboUI, Warning, TEXT("VehicleListView widget not found! Make sure it's bound in the Blueprint."));
    }

    // Initialize fade overlay to transparent and non-blocking
    if (Fade)
    {
        FLinearColor BrushColor = Fade->GetBrushColor();
        BrushColor.A = 0.0f;  // Start transparent
        Fade->SetBrushColor(BrushColor);

        // Make sure it doesn't block input - never catches mouse events
        Fade->SetVisibility(ESlateVisibility::HitTestInvisible);
    }
    else
    {
        UE_LOG(LogRealGazeboUI, Warning, TEXT("Fade border not found! Make sure it's bound in the Blueprint."));
    }

    // Bind reset button
    if (Reset_Button)
    {
        Reset_Button->OnClicked.AddDynamic(this, &URealGazeboMainWidget::OnResetButtonClicked);
    }
    else
    {
        UE_LOG(LogRealGazeboUI, Warning, TEXT("Reset_Button not found! Make sure it's bound in the Blueprint."));
    }

    // Start regular update timer
    if (UWorld* World = GetWorld())
    {
        float UpdateInterval = 1.0f / FMath::Max(UpdateFrequency, 1.0f);
        World->GetTimerManager().SetTimer(
            UpdateTimerHandle,
            this,
            &URealGazeboMainWidget::UpdateVehicleData,
            UpdateInterval,
            true
        );
        
        // Update timer started
    }
    
    // Initial data refresh
    RefreshVehicleList();
}

void URealGazeboMainWidget::NativeDestruct()
{
    // Destructing UI
    
    // Clear timer
    if (UWorld* World = GetWorld())
    {
        World->GetTimerManager().ClearTimer(UpdateTimerHandle);
    }
    
    // Clear all vehicle items
    ClearAllVehicles();
    
    Super::NativeDestruct();
}

void URealGazeboMainWidget::NativeTick(const FGeometry& MyGeometry, float InDeltaTime)
{
    Super::NativeTick(MyGeometry, InDeltaTime);
}

void URealGazeboMainWidget::InitializeSubsystemConnection()
{
    // Get bridge subsystem reference
    BridgeSubsystem = UGazeboBridgeSubsystem::GetBridgeSubsystem(this);
    
    if (BridgeSubsystem.IsValid())
    {
        // Connected to GazeboBridgeSubsystem
        
        // Note: Subsystem events will be handled through the update timer for now
        // Future enhancement: Add proper event handlers for OnVehicleSpawned and OnVehicleUpdated
    }
    else
    {
        UE_LOG(LogRealGazeboUI, Error, TEXT("Failed to get GazeboBridgeSubsystem! UI will not update automatically."));
    }
}

void URealGazeboMainWidget::UpdateVehicleData()
{
    if (!BridgeSubsystem.IsValid())
    {
        return;
    }
    
    double StartTime = FPlatformTime::Seconds();
    
    // Get current vehicle IDs from subsystem
    TArray<FVehicleID> CurrentVehicleIDs = BridgeSubsystem->GetAllVehicleIDs();
    
    // Track changes for performance
    bool bVehicleListChanged = false;
    
    // Add new vehicles or update existing ones
    for (const FVehicleID& VehicleID : CurrentVehicleIDs)
    {
        FVehicleRuntimeData RuntimeData = BridgeSubsystem->GetVehicleData(VehicleID);
        
        if (VehicleItemMap.Contains(VehicleID))
        {
            // Update existing vehicle
            UpdateVehicleInList(VehicleID, RuntimeData);
        }
        else
        {
            // Add new vehicle
            AddVehicleToList(VehicleID, RuntimeData);
            bVehicleListChanged = true;
        }
    }
    
    // Remove vehicles that no longer exist
    TArray<FVehicleID> VehiclesToRemove;
    for (const auto& Pair : VehicleItemMap)
    {
        if (!CurrentVehicleIDs.Contains(Pair.Key))
        {
            VehiclesToRemove.Add(Pair.Key);
            bVehicleListChanged = true;
        }
    }
    
    for (const FVehicleID& VehicleID : VehiclesToRemove)
    {
        RemoveVehicleFromList(VehicleID);
    }
    
    // Update connection status
    if (!BridgeSubsystem.IsValid())
    {
        return;
    }
    
    bool bIsConnected = BridgeSubsystem->IsBridgeActive();
    if (bIsConnected != bLastConnectionStatus)
    {
        bLastConnectionStatus = bIsConnected;
        
        FString StatusMessage = bIsConnected ? TEXT("Connected") : TEXT("Disconnected");
        OnConnectionStatusChanged(bIsConnected, StatusMessage);
    }
    
    
    if (bVehicleListChanged)
    {
        // Vehicle list updated - notify ViewerDirector to refresh its vehicle list
        if (ViewerDirector.IsValid())
        {
            ViewerDirector->RefreshVehicleList();
            UE_LOG(LogRealGazeboUI, Log, TEXT("MainWidget: Notified ViewerDirector to refresh vehicle list due to changes"));
        }
    }
}

URealGazeboVehicleListItem* URealGazeboMainWidget::AddVehicleToList(const FVehicleID& VehicleID, const FVehicleRuntimeData& RuntimeData)
{
    // Create new list item
    URealGazeboVehicleListItem* NewItem = NewObject<URealGazeboVehicleListItem>(this);
    if (!NewItem)
    {
        UE_LOG(LogRealGazeboUI, Error, TEXT("Failed to create vehicle list item for vehicle %s"), *VehicleID.ToString());
        return nullptr;
    }
    
    // Initialize item data
    NewItem->VehicleID = VehicleID;
    NewItem->VehicleTypeName = GetVehicleTypeName(RuntimeData.VehicleType);
    NewItem->VehicleName = GenerateVehicleDisplayName(VehicleID, RuntimeData.VehicleType);
    NewItem->UpdateFromRuntimeData(RuntimeData);
    
    // Add to map and ListView
    VehicleItemMap.Add(VehicleID, NewItem);
    
    if (VehicleListView)
    {
        VehicleListView->AddItem(NewItem);
    }
    
    // Added vehicle to list
    return NewItem;
}

void URealGazeboMainWidget::RemoveVehicleFromList(const FVehicleID& VehicleID)
{
    TObjectPtr<URealGazeboVehicleListItem>* ItemPtr = VehicleItemMap.Find(VehicleID);
    if (ItemPtr && *ItemPtr)
    {
        URealGazeboVehicleListItem* Item = *ItemPtr;
        
        // Remove from ListView
        if (VehicleListView)
        {
            VehicleListView->RemoveItem(Item);
        }
        
        // Remove from map
        VehicleItemMap.Remove(VehicleID);
        
        // Removed vehicle from list
    }
}

void URealGazeboMainWidget::UpdateVehicleInList(const FVehicleID& VehicleID, const FVehicleRuntimeData& RuntimeData)
{
    TObjectPtr<URealGazeboVehicleListItem>* ItemPtr = VehicleItemMap.Find(VehicleID);
    if (ItemPtr && *ItemPtr)
    {
        (*ItemPtr)->UpdateFromRuntimeData(RuntimeData);
        
        // Request ListView refresh for this item
        if (VehicleListView)
        {
            VehicleListView->RequestRefresh();
        }
    }
}


FString URealGazeboMainWidget::GetVehicleTypeName(uint8 VehicleType) const
{
    if (BridgeSubsystem.IsValid())
    {
        FBridgeVehicleConfigRow Config;
        if (BridgeSubsystem->GetVehicleConfig(VehicleType, Config))
        {
            return Config.VehicleName;
        }
    }
    
    // Fallback if not found in DataTable
    return FString::Printf(TEXT("Type_%d"), VehicleType);
}

FString URealGazeboMainWidget::GenerateVehicleDisplayName(const FVehicleID& VehicleID, uint8 VehicleType) const
{
    FString TypeName = GetVehicleTypeName(VehicleType);
    return FString::Printf(TEXT("%s_%d"), *TypeName, VehicleID.VehicleNum);
}

void URealGazeboMainWidget::OnVehicleItemSelectionChanged(UObject* SelectedItem)
{
    if (URealGazeboVehicleListItem* VehicleItem = Cast<URealGazeboVehicleListItem>(SelectedItem))
    {
        // Update current selection
        CurrentSelectedVehicleID = VehicleItem->VehicleID;

        // Notify ViewerDirector for camera integration
        if (ViewerDirector.IsValid())
        {
            AVehicleBasePawn* SelectedVehiclePawn = FindVehiclePawnByID(VehicleItem->VehicleID);
            if (SelectedVehiclePawn)
            {
                ViewerDirector->SetCurrentVehicle(SelectedVehiclePawn);
                UE_LOG(LogRealGazeboUI, Log, TEXT("MainWidget: Set camera target to vehicle %s (ID: %d_%d)"),
                       *SelectedVehiclePawn->GetName(),
                       VehicleItem->VehicleID.VehicleType,
                       VehicleItem->VehicleID.VehicleNum);
            }
            else
            {
                // Vehicle not found in world - clear camera target
                ViewerDirector->SetCurrentVehicle(nullptr);
                UE_LOG(LogRealGazeboUI, Warning, TEXT("MainWidget: Vehicle pawn not found for ID %d_%d, cleared camera target"),
                       VehicleItem->VehicleID.VehicleType,
                       VehicleItem->VehicleID.VehicleNum);
            }
        }
        else
        {
            UE_LOG(LogRealGazeboUI, Log, TEXT("MainWidget: No ViewerDirector available for camera integration"));
        }

        // Call Blueprint events
        OnVehicleSelected(VehicleItem);
        OnCameraTargetChanged(VehicleItem);
    }
    else
    {
        // Selection cleared
        CurrentSelectedVehicleID = FVehicleID(0, 0); // Invalid ID

        // Clear ViewerDirector target
        if (ViewerDirector.IsValid())
        {
            ViewerDirector->SetCurrentVehicle(nullptr);
            UE_LOG(LogRealGazeboUI, Log, TEXT("MainWidget: Cleared camera target (selection cleared)"));
        }

        // Notify Blueprint that camera target was cleared
        OnCameraTargetChanged(nullptr);
    }
}

void URealGazeboMainWidget::OnEntryWidgetGenerated(UUserWidget& GeneratedWidget)
{
    // This is called whenever a ListView entry widget is created or recycled
    if (URealGazeboVehicleEntry* VehicleEntry = Cast<URealGazeboVehicleEntry>(&GeneratedWidget))
    {
        // Entry widget generated/recycled

        // Configure DataTable if available
        if (VehicleTypeImageDataTable)
        {
            VehicleEntry->SetVehicleTypeImageDataTable(VehicleTypeImageDataTable);
        }

        // The widget will have its data set via NativeOnListItemObjectSet automatically.
    }
}


void URealGazeboMainWidget::ClearAllVehicles()
{
    if (VehicleListView)
    {
        VehicleListView->ClearListItems();
    }
    
    VehicleItemMap.Empty();
    // Cleared all vehicles from list
}

void URealGazeboMainWidget::RefreshVehicleList()
{
    ClearAllVehicles();
    UpdateVehicleData();
}

TArray<URealGazeboVehicleListItem*> URealGazeboMainWidget::GetAllVehicleItems() const
{
    TArray<URealGazeboVehicleListItem*> Items;
    for (const auto& Pair : VehicleItemMap)
    {
        Items.Add(Pair.Value);
    }
    return Items;
}

URealGazeboVehicleListItem* URealGazeboMainWidget::GetVehicleItem(const FVehicleID& VehicleID) const
{
    if (const TObjectPtr<URealGazeboVehicleListItem>* ItemPtr = VehicleItemMap.Find(VehicleID))
    {
        return *ItemPtr;
    }
    return nullptr;
}

TArray<URealGazeboVehicleListItem*> URealGazeboMainWidget::GetSelectedVehicleItems() const
{
    TArray<URealGazeboVehicleListItem*> SelectedItems;
    
    if (VehicleListView)
    {
        TArray<UObject*> SelectedObjects;
        VehicleListView->GetSelectedItems(SelectedObjects);
        for (UObject* Object : SelectedObjects)
        {
            if (URealGazeboVehicleListItem* VehicleItem = Cast<URealGazeboVehicleListItem>(Object))
            {
                SelectedItems.Add(VehicleItem);
            }
        }
    }
    
    return SelectedItems;
}




void URealGazeboMainWidget::SetSelectedVehicle(FVehicleID VehicleID)
{
    // Check if already selected
    if (CurrentSelectedVehicleID == VehicleID)
    {
        return;
    }

    FVehicleID PreviousSelectedVehicleID = CurrentSelectedVehicleID;
    CurrentSelectedVehicleID = VehicleID;

    // Vehicle selection changed

    // Selection is now handled by ListView - no manual widget updates needed
    // Vehicle selection handled by ListView
}

void URealGazeboMainWidget::ClearVehicleSelection()
{
    if (CurrentSelectedVehicleID.VehicleNum == 0 && CurrentSelectedVehicleID.VehicleType == 0)
    {
        // Already cleared
        return;
    }

    FVehicleID PreviousSelectedVehicleID = CurrentSelectedVehicleID;
    CurrentSelectedVehicleID = FVehicleID(0, 0); // Invalid ID

    // Cleared vehicle selection

    // Clear ListView selection - this will automatically update visual feedback
    if (VehicleListView)
    {
        VehicleListView->ClearSelection();
        // Cleared ListView selection
    }
}

void URealGazeboMainWidget::SetVehicleTypeImageDataTable(UDataTable* DataTable)
{
    VehicleTypeImageDataTable = DataTable;

    // Configure all currently displayed vehicle entry widgets
    if (VehicleListView)
    {
        // Get all displayed widgets and configure them
        TArray<UUserWidget*> DisplayedEntryWidgets = VehicleListView->GetDisplayedEntryWidgets();
        for (UUserWidget* Widget : DisplayedEntryWidgets)
        {
            if (URealGazeboVehicleEntry* VehicleEntry = Cast<URealGazeboVehicleEntry>(Widget))
            {
                VehicleEntry->SetVehicleTypeImageDataTable(DataTable);
            }
        }
    }
}

void URealGazeboMainWidget::SetViewerDirector(ARealGazeboViewerDirector* InViewerDirector)
{
    ViewerDirector = InViewerDirector;
    UE_LOG(LogRealGazeboUI, Log, TEXT("MainWidget: ViewerDirector reference set for camera integration"));
}

AVehicleBasePawn* URealGazeboMainWidget::FindVehiclePawnByID(const FVehicleID& VehicleID) const
{
    UWorld* World = GetWorld();
    if (!World)
    {
        return nullptr;
    }

    // Find vehicle pawn by searching all VehicleBasePawn actors
    TArray<AActor*> FoundActors;
    UGameplayStatics::GetAllActorsOfClass(World, AVehicleBasePawn::StaticClass(), FoundActors);

    for (AActor* Actor : FoundActors)
    {
        if (AVehicleBasePawn* VehiclePawn = Cast<AVehicleBasePawn>(Actor))
        {
            if (VehiclePawn->VehicleID == VehicleID)
            {
                return VehiclePawn;
            }
        }
    }

    return nullptr;
}

//----------------------------------------------------------
// Reset Button & Fade Functionality
//----------------------------------------------------------

void URealGazeboMainWidget::OnResetButtonClicked()
{
    UE_LOG(LogRealGazeboUI, Log, TEXT("Reset button clicked - starting fade and reload"));

    // Reset fade timer
    FadeElapsedTime = 0.0f;

    // Start fade animation timer (60 FPS for smooth animation)
    if (UWorld* World = GetWorld())
    {
        World->GetTimerManager().SetTimer(
            FadeTimerHandle,
            this,
            &URealGazeboMainWidget::UpdateFadeAlpha,
            1.0f / 60.0f,  // Update at 60 FPS
            true           // Loop
        );
    }
}

void URealGazeboMainWidget::UpdateFadeAlpha()
{
    FadeElapsedTime += (1.0f / 60.0f);
    float Alpha = FMath::Clamp(FadeElapsedTime / FadeDuration, 0.0f, 1.0f);

    // Update border alpha
    if (Fade)
    {
        FLinearColor BrushColor = Fade->GetBrushColor();
        BrushColor.A = Alpha;
        Fade->SetBrushColor(BrushColor);
    }

    // When fade completes (fully opaque), reload level
    if (Alpha >= 1.0f)
    {
        if (UWorld* World = GetWorld())
        {
            World->GetTimerManager().ClearTimer(FadeTimerHandle);
        }

        ReloadCurrentLevel();
    }
}

void URealGazeboMainWidget::ReloadCurrentLevel()
{
    UE_LOG(LogRealGazeboUI, Log, TEXT("Reloading current level"));

    // Get current level name and reload it
    FString CurrentLevelName = UGameplayStatics::GetCurrentLevelName(this);
    UGameplayStatics::OpenLevel(this, FName(*CurrentLevelName));

    // Note: After reload, NativeConstruct will be called again
    // and Fade border will be reset to alpha 0 (transparent)
}

